### ISSUE TITLE
ESlint

### ISSUE THREAD

**Issue by zsmoore** [project-ivi/ivi#108]
Modify docs to remove use of jest when testing and just have `npm run test`

Add linting `eslint` to dependencies and add it to travis so code has to conform to checkstyle before being accepted.

Reflect all of these changes in travis so we don't have different dependencies on dev vs travis

**Comment by gjbunyea** [comment]
jest removed from docs, travis, etc..

adding eslint now could be dangerous - it might say all this code sucks and be mad, but ill try and see

**Comment by gjbunyea** [comment]
Enforce: No semi colons, 2 space indent

**Comment by zsmoore** [comment]
Can we enforce semi colons? I was following strict JS conventions which requires all code to end in semi-colon.

**Comment by gjbunyea** [comment]
@angushtlam, @noahpoz  both wanted no semis. Also gonna add single-quote enforcement

**Comment by gjbunyea** [comment]
Add: Space around operators, space after for,if space after condition, no trailing white space, semis back, max one-line break, 120 char max,  

Space before and after braces, space after comma, enforce trailing commas

**Comment by gjbunyea** [comment]
@angushtlam were there specific keywords we don't want to have spaces around? https://eslint.org/docs/rules/keyword-spacing
