### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by gjbunyea** [project-ivi/ivi#12]

**Comment by zsmoore** [comment]
Angus and I discussed this earlier in the week.  

The API design will evolve over time however, the beginning API design will be put on a wiki page.  

Will close after wiki is created.

**Comment by zsmoore** [comment]
https://github.com/project-ivi/ivi/wiki/Interpreter-Basic-Design  
Link for basic design doc.  
@gjbunyea Feel free to close this issue if you are happy with the doc in its current state.

**Comment by gjbunyea** [comment]
Looks good! It'll definitely evolve but great for now
