### ISSUE TITLE
Console's not working

### ISSUE THREAD

**Issue by rachelaroberts** [project-ivi/ivi#126]
## Context

**Bug fix? yes**

I tried to perform a math operation on two variables and it nothing happens.

### Current v Expected Results

 It runs with no output. It should give me a console error because this doesn't support math yet.

## Repro Steps 

```
var x;
x = 5;
var y;
y = 6;
var t;
t = x + y;
```

## Acceptance Criteria

Shouldn't run, should give you console error.

**Comment by gjbunyea** [comment]
Not sure if this is a console or interpreter error. Maybe we can flag all math operations as unsupported?

**Comment by zsmoore** [comment]
We don't support arithmetic operations as per our MVP.  I'll toss a hotfix in in order to spit out unsupported into the console.

Thanks for pointing this out.

**Comment by zsmoore** [comment]
Fix going in at #136
