### ISSUE TITLE
Interpreter drops last expression from evaluation

### ISSUE THREAD

**Issue by angushtlam** [project-ivi/ivi#58]
The `evaluate` function currently ignores the last operation from the code inputted.

Input:
```
var a=2;
var b = 3
c = 4;
d = 5
var e;
f;
g
// Comments work in the code only at beginning of line
/* Block
    Comments
    Work
    Too
 */
console.log('hello');
var h = 2;
```

Expected Output:
There should be an additional entry in the array response from `evaluate` that indicates the change in variable for `var h = 2;`. Right now it is completely dropped.

**Comment by zsmoore** [comment]
@angushtlam Can you confirm this on my PR branch? I am not seeing the issue come up

**Comment by gjbunyea** [comment]
I'm also not seeing this issue on zach's branch

**Comment by zsmoore** [comment]
Found the bug will get fixed in my next PR
