### ISSUE TITLE
Mock up visualizer styles

### ISSUE THREAD

**Issue by zsmoore** [project-ivi/ivi#71]

**Comment by gjbunyea** [comment]
Some new colors:
blue: #00c9fe    
aqua: #00d4df                                                    
teal: #00dab4                                                    
peach: #ffb5b4                                                   
pink: #ff96b4                                                    
deepblue: #0096b4                                                
perriwinkle: #0069fbff                                           
lavender: #af96fb                                                
orange: #ff8b6a                                                  
golden: #ffbf00                                                  
hotpink: #ff00c3                                                 
darkblue: #0000c3

**Comment by zsmoore** [comment]
Was shared over outside communication and implemented. Good stuff
